"""Add cover_filename to User

Revision ID: 160508a55bac
Revises: d28fc15f234a
Create Date: 2025-11-03 10:20:24.853104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160508a55bac'
down_revision = 'd28fc15f234a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_filename', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cover_filename')

    # ### end Alembic commands ###
